### ISSUE TITLE
how to set the modal`s width

### ISSUE THREAD

**Issue by yunClouds** [DanielYKPan/ng2-date-time-picker#16]
when i set the [mode]="'dropdown'"  , i meet a CSS problem:
![image](https://cloud.githubusercontent.com/assets/26613310/24575073/20b06afa-16cf-11e7-86e1-6d134bf7be51.png)
 so  i want to redefined the modal`s width

**Comment by DanielYKPan** [comment]
@yunClouds 
Use the latest version ng2-date-time-picker@2.1.0
It should be all right.

BTW, I know Chinese. Have fun.

**Comment by yunClouds** [comment]
@DanielYKPan 
First of all, Thanks alot Daniel.  I change to 
 the version@2.1.0 ,and its better than the old version, but it still has a little problem as shown in the figure:
![image](https://cloud.githubusercontent.com/assets/26613310/24576250/eb5808e2-16ea-11e7-8794-4000f7b0f34c.png)

BTW, Welcome to travel in China.

**Comment by DanielYKPan** [comment]
@yunClouds 
That's odd.
Are you using any other third party css like bootstrap?

**Comment by DanielYKPan** [comment]
@yunClouds 
I tried it on a clean css style set. It works well. and I also try it with Bootstrap, it works well too. Do you projects have any special css set? What environment are you running?

**Comment by yunClouds** [comment]
@DanielYKPan 
really , but I do not  have use bootstrap , and I try to create a new project , only use ng2-date-time-picker , that problem still exist。

**Comment by yunClouds** [comment]
@DanielYKPan
Then ,  I found that if these two css class set like this: 
 .small-mode .picker-calendar .picker-weekday {
  font-size: 12px;
  line-height: 20px;
  padding-left: 0px;
}

.small-mode .picker-banner-moment .moment-date .big {
  font-size: 18.328px;
  line-height: 40px;
}
It works well:
so I do not know if it`s possible could you update itThen ,  I found that if these two css class set like this: 
 .small-mode .picker-calendar .picker-weekday {
  font-size: 12px;
  line-height: 20px;
  padding-left: 0px;
}

.small-mode .picker-banner-moment .moment-date .big {
  font-size: 18.328px;
  line-height: 40px;
}
It works well, so I do not know if it`s possible could you update it. Anyway, Thanks once again

**Comment by DanielYKPan** [comment]
@yunClouds 
I see the problem. It was NOT about the font-size or the padding. It is about the box-sizing. Because I set my box-sizing: border-box on my app module css, not in date-time-picker module. And this caused the ugly style.
It has been fixed on the latest version.

**Comment by yunClouds** [comment]
@DanielYKPan
Hello ,Daniel, It`s great that supports Angular 4 , and the week`s  style is ok! but the problem as shown in the figure:
![error](https://cloud.githubusercontent.com/assets/26613310/24640656/284d5864-192b-11e7-8398-92a64962989b.png)
is  still happen

**Comment by DanielYKPan** [comment]
@yunClouds 
It is odd.
What css style are you running at?

Because in my test project, I don't have this style problem
<img width="115" alt="screen shot 2017-04-04 at 1 42 18 pm" src="https://cloud.githubusercontent.com/assets/5952855/24640732/d2e02228-193c-11e7-95b3-7df27640db76.png">

**Comment by yunClouds** [comment]
@DanielYKPan
ohh, it`s  perplexing，I test it in an new project ,and the project without any css style.  I user the Chrome ，Do you use this browser too?

**Comment by DanielYKPan** [comment]
@yunClouds 
Yes. I tested in Chrome Safari Firefox IE
 Any new project without any css style works well
